Repository Side-Effect-Team/side-effect-backend, pull requests merged in 2023-06, with the labels that each got.

#82 Feat/token 로그아웃 기능 구현과 TokenProvider 수정
  server/build.gradle
  server/src/main/java/sideeffect/project/ProjectApplication.java
  server/src/main/java/sideeffect/project/config/security/AuthProperties.java
  server/src/main/java/sideeffect/project/controller/OauthController.java
  server/src/main/java/sideeffect/project/controller/RefreshTokenController.java
  server/src/main/java/sideeffect/project/dto/user/RefreshTokenResponse.java
  server/src/main/java/sideeffect/project/security/JwtTokenProvider.java
  server/src/main/java/sideeffect/project/security/LoginSuccessHandler.java
  server/src/main/java/sideeffect/project/security/RefreshTokenProvider.java
  server/src/main/java/sideeffect/project/security/UserDetailsServiceImpl.java
  server/src/test/java/sideeffect/project/security/JwtTokenProviderTest.java
  server/src/test/java/sideeffect/project/security/RefreshTokenProviderTest.java
Labels: feat, refactor

#85 Feat/auth oauth login 필터 내에 동작하도록 변경
  server/src/main/java/sideeffect/project/config/WebSecurityConfig.java
  server/src/main/java/sideeffect/project/controller/OauthController.java
  server/src/main/java/sideeffect/project/security/SecurityExceptionHandlerFilter.java
  server/src/main/java/sideeffect/project/security/oauth/Oauth2AuthenticationManager.java
  server/src/main/java/sideeffect/project/security/oauth/Oauth2LoginFilter.java
Labels: refactor

#86 refactor: 지원(팀원) 목록 API career, githubUrl field 추가
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantInfoResponse.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantListResponse.java
  server/src/main/java/sideeffect/project/repository/RecruitBoardRepository.java
Labels: refactor

#87 refactor: 모집게시판 스크롤조회 작성일 반환값 수정
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardResponse.java
Labels: refactor

#91 Feat/freeboard 랭킹 기능 수정
  server/src/main/java/sideeffect/project/controller/FreeBoardController.java
  server/src/main/java/sideeffect/project/dto/freeboard/RankResponse.java
  server/src/main/java/sideeffect/project/repository/freeboard/FreeBoardRepositoryCustom.java
  server/src/main/java/sideeffect/project/repository/freeboard/FreeBoardRepositoryImpl.java
  server/src/main/java/sideeffect/project/service/FreeBoardService.java
  server/src/test/java/sideeffect/project/controller/FreeBoardControllerTest.java
Labels: refactor

#94 Feat/rest docs api
  server/src/docs/asciidoc/Applicant-API.adoc
  server/src/docs/asciidoc/RecruitBoard-API.adoc
  server/src/docs/asciidoc/RecruitComments-API.adoc
  server/src/docs/asciidoc/index.adoc
  server/src/test/java/sideeffect/project/controller/ApplicantControllerTest.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/controller/RecruitCommentControllerTest.java
Labels: test

#95 refactor: 모집 게시글 스크롤 조회 response 댓글 수 필드 추가
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardResponse.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
Labels: refactor
