Repository Side-Effect-Team/side-effect-backend, pull requests merged in 2023-05, with the labels that each got.

#21 Feat/common Querydsl관련 설정
  server/src/main/java/sideeffect/project/config/QuerydslConfiguration.java
  server/src/test/java/sideeffect/project/common/jpa/TestDataRepository.java
  server/src/test/java/sideeffect/project/common/jpa/TestQuerydslConfiguration.java
  server/src/test/java/sideeffect/project/domain/common/BaseTimeEntityTest.java
Labels: feat

#23 fix: Fix issue #22
  server/src/test/java/sideeffect/project/repository/PositionRepositoryTest.java
  server/src/test/java/sideeffect/project/repository/RecommendRepositoryTest.java
  server/src/test/java/sideeffect/project/repository/RecruitBoardRepositoryTest.java
  server/src/test/java/sideeffect/project/repository/StackRepositoryTest.java
  server/src/test/java/sideeffect/project/repository/UserRepositoryTest.java
Labels: fix

#29 Feat/applicant 모집 게시판 지원 기능 구현
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/controller/ApplicantController.java
  server/src/main/java/sideeffect/project/domain/applicant/Applicant.java
  server/src/main/java/sideeffect/project/domain/applicant/ApplicantStatus.java
  server/src/main/java/sideeffect/project/domain/recruit/BoardPosition.java
  server/src/main/java/sideeffect/project/domain/recruit/RecruitBoard.java
  server/src/main/java/sideeffect/project/domain/user/User.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantInfoResponse.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantListResponse.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantPositionResponse.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantReleaseRequest.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantRequest.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantResponse.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantUpdateRequest.java
  server/src/main/java/sideeffect/project/dto/recruit/BoardPositionResponse.java
  server/src/main/java/sideeffect/project/repository/ApplicantRepository.java
  server/src/main/java/sideeffect/project/repository/BoardPositionRepository.java
  server/src/main/java/sideeffect/project/repository/RecruitBoardRepository.java
  server/src/main/java/sideeffect/project/service/ApplicantService.java
  server/src/test/java/sideeffect/project/controller/ApplicantControllerTest.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/domain/applicant/ApplicantTest.java
  server/src/test/java/sideeffect/project/domain/recruit/BoardPositionTest.java
  server/src/test/java/sideeffect/project/repository/BoardPositionRepositoryTest.java
  server/src/test/java/sideeffect/project/repository/RecruitBoardRepositoryTest.java
  server/src/test/java/sideeffect/project/service/ApplicantServiceTest.java
Labels: feat

#34 Feat/freeboard API 수정 및 데이터베이스 변경
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/controller/FreeBoardController.java
  server/src/main/java/sideeffect/project/domain/freeboard/FreeBoard.java
  server/src/main/java/sideeffect/project/domain/like/Like.java
  server/src/main/java/sideeffect/project/domain/user/User.java
  server/src/main/java/sideeffect/project/dto/freeboard/DetailedFreeBoardResponse.java
  server/src/main/java/sideeffect/project/dto/freeboard/FreeBoardKeyWordRequest.java
  server/src/main/java/sideeffect/project/dto/freeboard/FreeBoardRequest.java
  server/src/main/java/sideeffect/project/dto/freeboard/FreeBoardResponse.java
  server/src/main/java/sideeffect/project/dto/freeboard/FreeBoardScrollDto.java
  server/src/main/java/sideeffect/project/dto/like/LikeRequest.java
  server/src/main/java/sideeffect/project/dto/like/LikeResponse.java
  server/src/main/java/sideeffect/project/dto/like/LikeResult.java
  server/src/main/java/sideeffect/project/dto/recommend/RecommendResult.java
  server/src/main/java/sideeffect/project/repository/FreeBoardRepository.java
  server/src/main/java/sideeffect/project/repository/LikeRepository.java
  server/src/main/java/sideeffect/project/repository/RecommendRepository.java
  server/src/main/java/sideeffect/project/repository/freeboard/FreeBoardRepositoryImpl.java
  server/src/main/java/sideeffect/project/service/FreeBoardService.java
  server/src/main/java/sideeffect/project/service/LikeService.java
  server/src/test/java/sideeffect/project/controller/FreeBoardControllerTest.java
  server/src/test/java/sideeffect/project/domain/freeboard/FreeBoardTest.java
  server/src/test/java/sideeffect/project/domain/like/LikeTest.java
  server/src/test/java/sideeffect/project/repository/FreeBoardRepositoryTest.java
  server/src/test/java/sideeffect/project/repository/LikeRepositoryTest.java
  server/src/test/java/sideeffect/project/service/FreeBoardServiceTest.java
  server/src/test/java/sideeffect/project/service/LikeServiceTest.java
Labels: feat

#37 Feat/applicant 모집 게시글 포지션 지원기능 API 수정
  server/src/main/java/sideeffect/project/common/converter/ApplicantStatusRequestConverter.java
  server/src/main/java/sideeffect/project/config/WebMvcConfig.java
  server/src/main/java/sideeffect/project/controller/ApplicantController.java
  server/src/main/java/sideeffect/project/domain/applicant/ApplicantStatus.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantInfoResponse.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantListResponse.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantRequest.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantUpdateRequest.java
  server/src/main/java/sideeffect/project/repository/RecruitBoardRepository.java
  server/src/main/java/sideeffect/project/service/ApplicantService.java
  server/src/test/java/sideeffect/project/controller/ApplicantControllerTest.java
  server/src/test/java/sideeffect/project/service/ApplicantServiceTest.java
Labels: feat, refactor

#41 feat: 모집 게시판 전체 조회 기능 구현
  server/src/main/java/sideeffect/project/controller/RecruitBoardController.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardAllResponse.java
  server/src/main/java/sideeffect/project/service/RecruitBoardService.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/service/RecruitBoardServiceTest.java
Labels: feat

#44 Feat/applicant 지원자 또는 팀원 목록 response 수정
  server/src/main/java/sideeffect/project/controller/ApplicantController.java
  server/src/main/java/sideeffect/project/domain/position/PositionType.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantListResponse.java
  server/src/main/java/sideeffect/project/dto/applicant/ApplicantPositionResponse.java
  server/src/main/java/sideeffect/project/service/ApplicantService.java
  server/src/test/java/sideeffect/project/controller/ApplicantControllerTest.java
  server/src/test/java/sideeffect/project/service/ApplicantServiceTest.java
Labels: refactor

#45 Feat/applicant 지원자 또는 팀원 목록에 없는 포지션 포함하도록 수정
  server/src/main/java/sideeffect/project/service/ApplicantService.java
  server/src/test/java/sideeffect/project/service/ApplicantServiceTest.java
Labels: refactor

#46 Feat/recruit board 모집 게시판 좋아요(추천) 기능 구현 및 게시판 수정 API 변경
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/controller/RecruitBoardController.java
  server/src/main/java/sideeffect/project/domain/like/RecruitLike.java
  server/src/main/java/sideeffect/project/domain/recruit/RecruitBoard.java
  server/src/main/java/sideeffect/project/domain/user/User.java
  server/src/main/java/sideeffect/project/dto/like/RecruitLikeResponse.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardResponse.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardUpdateRequest.java
  server/src/main/java/sideeffect/project/repository/RecruitLikeRepository.java
  server/src/main/java/sideeffect/project/service/RecruitBoardService.java
  server/src/main/java/sideeffect/project/service/RecruitLikeService.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/service/RecruitBoardServiceTest.java
  server/src/test/java/sideeffect/project/service/RecruitLikeServiceTest.java
Labels: feat, refactor

#47 Feat/freeboard 조회 관련 기능과 소프트 삭제 기능 추가
  server/src/main/java/sideeffect/project/common/converter/OrderTypeRequestConverter.java
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/controller/FreeBoardController.java
  server/src/main/java/sideeffect/project/domain/freeboard/FreeBoard.java
  server/src/main/java/sideeffect/project/dto/freeboard/FreeBoardKeyWordRequest.java
  server/src/main/java/sideeffect/project/dto/freeboard/FreeBoardResponse.java
  server/src/main/java/sideeffect/project/dto/freeboard/FreeBoardScrollDto.java
  server/src/main/java/sideeffect/project/dto/freeboard/FreeBoardScrollRequest.java
  server/src/main/java/sideeffect/project/dto/freeboard/OrderType.java
  server/src/main/java/sideeffect/project/repository/FreeBoardRepository.java
  server/src/main/java/sideeffect/project/repository/freeboard/FreeBoardRepositoryCustom.java
  server/src/main/java/sideeffect/project/repository/freeboard/FreeBoardRepositoryImpl.java
  server/src/main/java/sideeffect/project/service/FreeBoardService.java
  server/src/test/java/sideeffect/project/convertor/OrderTypeConverterTest.java
  server/src/test/java/sideeffect/project/dto/freeboard/OrderTypeTest.java
  server/src/test/java/sideeffect/project/repository/FreeBoardRepositoryTest.java
  server/src/test/java/sideeffect/project/service/FreeBoardServiceTest.java
Labels: feat

#48 Feat/security 예외처리 필터 및 구글 API 구현
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/common/exception/JoinException.java
  server/src/main/java/sideeffect/project/config/WebSecurityConfig.java
  server/src/main/java/sideeffect/project/dto/user/GoogleUser.java
  server/src/main/java/sideeffect/project/security/CustomAuthenticationProvider.java
  server/src/main/java/sideeffect/project/security/ExceptionHandlerFilter.java
  server/src/main/java/sideeffect/project/security/JwtFilter.java
  server/src/main/java/sideeffect/project/security/JwtTokenProvider.java
  server/src/main/java/sideeffect/project/security/LoginFilter.java
  server/src/main/java/sideeffect/project/security/LoginSuccessHandler.java
  server/src/main/java/sideeffect/project/security/UserDetailsServiceImpl.java
Labels: feat

#50 Feat/comment 댓글과 추천 API 구현
  server/src/main/java/sideeffect/project/config/WebSecurityConfig.java
  server/src/main/java/sideeffect/project/controller/CommentController.java
  server/src/main/java/sideeffect/project/controller/LikeController.java
  server/src/main/java/sideeffect/project/domain/freeboard/FreeBoard.java
  server/src/main/java/sideeffect/project/dto/comment/CommentRequest.java
  server/src/main/java/sideeffect/project/dto/like/LikeRequest.java
  server/src/main/java/sideeffect/project/repository/FreeBoardRepository.java
  server/src/main/java/sideeffect/project/repository/LikeRepository.java
  server/src/main/java/sideeffect/project/service/CommentService.java
  server/src/main/java/sideeffect/project/service/LikeService.java
  server/src/test/java/sideeffect/project/controller/CommentControllerTest.java
  server/src/test/java/sideeffect/project/controller/LikeControllerTest.java
  server/src/test/java/sideeffect/project/repository/LikeRepositoryTest.java
  server/src/test/java/sideeffect/project/service/CommentServiceTest.java
  server/src/test/java/sideeffect/project/service/LikeServiceTest.java
Labels: feat, refactor

#51 Feat/notification Notification init
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/controller/NotificationController.java
  server/src/main/java/sideeffect/project/domain/notification/Notification.java
  server/src/main/java/sideeffect/project/domain/user/User.java
  server/src/main/java/sideeffect/project/dto/notification/NotificationResponse.java
  server/src/main/java/sideeffect/project/repository/NotificationRepository.java
  server/src/main/java/sideeffect/project/service/NotificationService.java
Labels: feat

#52 Feat/recruit board 파일 공통 로직 및 모집 게시판 이미지 처리 기능 구현
  server/src/main/java/sideeffect/project/common/annotation/ValidImageFile.java
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/common/fileupload/FilePath.java
  server/src/main/java/sideeffect/project/common/fileupload/ImageType.java
  server/src/main/java/sideeffect/project/common/fileupload/service/FilePathService.java
  server/src/main/java/sideeffect/project/common/fileupload/service/FileUploadService.java
  server/src/main/java/sideeffect/project/common/fileupload/service/RecruitUploadService.java
  server/src/main/java/sideeffect/project/common/validator/ImageFileValidator.java
  server/src/main/java/sideeffect/project/controller/RecruitBoardController.java
  server/src/main/java/sideeffect/project/domain/recruit/RecruitBoard.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardRequest.java
  server/src/main/java/sideeffect/project/service/RecruitBoardService.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/service/RecruitBoardServiceTest.java
Labels: feat

#53 refactor: 모집 게시판 이미지 업로드 구조 수정
  server/src/main/java/sideeffect/project/controller/RecruitBoardController.java
  server/src/main/java/sideeffect/project/service/RecruitBoardService.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/service/RecruitBoardServiceTest.java
Labels: refactor

#56 Feat/email 이메일 알림 기능 구현
  server/build.gradle
  server/src/main/java/sideeffect/project/config/AsyncConfig.java
  server/src/main/java/sideeffect/project/domain/notification/MessageConstruct.java
  server/src/main/java/sideeffect/project/service/ApplicantService.java
  server/src/main/java/sideeffect/project/service/MailService.java
  server/src/main/resources/application.properties
  server/src/main/resources/mail-templates/approved.html
  server/src/main/resources/mail-templates/pending.html
  server/src/main/resources/mail-templates/rejected.html
Labels: feat

#58 Feat/applicant 지원 취소 기능 구현
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/controller/ApplicantController.java
  server/src/main/java/sideeffect/project/service/ApplicantService.java
  server/src/test/java/sideeffect/project/controller/ApplicantControllerTest.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/service/ApplicantServiceTest.java
Labels: feat

#59 Feat/freeboard 자랑게시판 이미지 업로드 기능과 랭킹 기능 구현
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/common/fileupload/service/FreeBoardUploadService.java
  server/src/main/java/sideeffect/project/controller/FreeBoardController.java
  server/src/main/java/sideeffect/project/dto/freeboard/FreeBoardRequest.java
  server/src/main/java/sideeffect/project/repository/FreeBoardRepository.java
  server/src/main/java/sideeffect/project/repository/freeboard/FreeBoardRepositoryCustom.java
  server/src/main/java/sideeffect/project/repository/freeboard/FreeBoardRepositoryImpl.java
  server/src/main/java/sideeffect/project/service/CommentService.java
  server/src/main/java/sideeffect/project/service/FreeBoardService.java
  server/src/test/java/sideeffect/project/controller/FreeBoardControllerTest.java
  server/src/test/java/sideeffect/project/repository/FreeBoardRepositoryTest.java
  server/src/test/java/sideeffect/project/service/ApplicantServiceTest.java
  server/src/test/java/sideeffect/project/service/FreeBoardServiceTest.java
  server/src/test/java/sideeffect/project/service/RecruitBoardServiceTest.java
Labels: feat

#60 Feat/recruit board 모집 게시판 validation 및 Bean Validation 예외 처리 구현
  server/src/main/java/sideeffect/project/common/advice/GlobalExceptionHandler.java
  server/src/main/java/sideeffect/project/common/dto/ErrorObject.java
  server/src/main/java/sideeffect/project/domain/recruit/RecruitBoard.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardRequest.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardUpdateRequest.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
Labels: feat

#61 Feat/security Social 로그인 구현
  server/src/main/java/sideeffect/project/common/advice/GlobalExceptionHandler.java
  server/src/main/java/sideeffect/project/common/dto/JoinErrorResponse.java
  server/src/main/java/sideeffect/project/common/exception/JoinException.java
  server/src/main/java/sideeffect/project/config/WebSecurityConfig.java
  server/src/main/java/sideeffect/project/controller/OauthController.java
  server/src/main/java/sideeffect/project/dto/user/ResponseUserInfo.java
  server/src/main/java/sideeffect/project/security/CustomAuthenticationProvider.java
  server/src/main/java/sideeffect/project/security/ExceptionHandlerFilter.java
  server/src/main/java/sideeffect/project/security/JwtTokenProvider.java
  server/src/main/java/sideeffect/project/security/LoginFilter.java
  server/src/main/java/sideeffect/project/security/LoginSuccessHandler.java
  server/src/main/java/sideeffect/project/security/oauth/GoogleOAuth.java
  server/src/main/java/sideeffect/project/security/oauth/GoogleUser.java
  server/src/main/java/sideeffect/project/security/oauth/KakaoOAuth.java
  server/src/main/java/sideeffect/project/security/oauth/KakaoUser.java
  server/src/main/java/sideeffect/project/security/oauth/Oauth.java
  server/src/main/java/sideeffect/project/service/OauthService.java
  server/src/main/java/sideeffect/project/service/UserService.java
Labels: feat

#67 Feat/applicant 모집게시판 포지션 지원, 좋아요 코드 리팩토링
  server/src/main/java/sideeffect/project/controller/ApplicantController.java
  server/src/main/java/sideeffect/project/controller/RecruitBoardController.java
  server/src/main/java/sideeffect/project/domain/like/RecruitLike.java
  server/src/main/java/sideeffect/project/repository/BoardPositionRepository.java
  server/src/main/java/sideeffect/project/repository/RecruitBoardCustomRepository.java
  server/src/main/java/sideeffect/project/repository/RecruitBoardCustomRepositoryImpl.java
  server/src/main/java/sideeffect/project/repository/RecruitBoardRepository.java
  server/src/main/java/sideeffect/project/service/ApplicantService.java
  server/src/main/java/sideeffect/project/service/RecruitLikeService.java
  server/src/test/java/sideeffect/project/controller/ApplicantControllerTest.java
  server/src/test/java/sideeffect/project/service/ApplicantServiceTest.java
  server/src/test/java/sideeffect/project/service/RecruitLikeServiceTest.java
Labels: refactor

#70 Feat/token refresh token 기능 구현
  server/src/main/java/sideeffect/project/config/JpaConfig.java
  server/src/main/java/sideeffect/project/config/RedisConfig.java
  server/src/main/java/sideeffect/project/config/WebSecurityConfig.java
  server/src/main/java/sideeffect/project/controller/OauthController.java
  server/src/main/java/sideeffect/project/controller/RefreshTokenController.java
  server/src/main/java/sideeffect/project/redis/RefreshTokenRepository.java
  server/src/main/java/sideeffect/project/repository/UserRepository.java
  server/src/main/java/sideeffect/project/repository/user/UserRepositoryCustom.java
  server/src/main/java/sideeffect/project/repository/user/UserRepositoryImpl.java
  server/src/main/java/sideeffect/project/security/JwtTokenProvider.java
  server/src/main/java/sideeffect/project/security/LoginSuccessHandler.java
  server/src/main/java/sideeffect/project/security/RefreshTokenProvider.java
  server/src/main/java/sideeffect/project/service/OauthService.java
  server/src/main/java/sideeffect/project/service/RefreshTokenService.java
  server/src/test/java/sideeffect/project/common/jpa/TestQuerydslConfiguration.java
  server/src/test/java/sideeffect/project/controller/CommentControllerTest.java
  server/src/test/java/sideeffect/project/controller/FreeBoardControllerTest.java
  server/src/test/java/sideeffect/project/controller/LikeControllerTest.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/repository/UserRepositoryTest.java
  server/src/test/java/sideeffect/project/security/RefreshTokenProviderTest.java
Labels: feat

#74 Feat/recruit board 모집게시판 좋아요 여부 로직 추가 및 무한 스크롤 쿼리 개선
  server/src/main/java/sideeffect/project/controller/RecruitBoardController.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardAndLikeDto.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardResponse.java
  server/src/main/java/sideeffect/project/repository/RecruitBoardCustomRepository.java
  server/src/main/java/sideeffect/project/repository/RecruitBoardCustomRepositoryImpl.java
  server/src/main/java/sideeffect/project/service/RecruitBoardService.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/repository/RecruitBoardRepositoryTest.java
  server/src/test/java/sideeffect/project/service/RecruitBoardServiceTest.java
Labels: feat, refactor

#75 Feat/freeboard 상세 게시물 조회 기능 수정과 댓글 기능 버그 수정
  server/src/main/java/sideeffect/project/controller/CommentController.java
  server/src/main/java/sideeffect/project/controller/FreeBoardController.java
  server/src/main/java/sideeffect/project/domain/freeboard/FreeBoard.java
  server/src/main/java/sideeffect/project/domain/user/User.java
  server/src/main/java/sideeffect/project/dto/comment/CommentUpdateRequest.java
  server/src/main/java/sideeffect/project/dto/freeboard/DetailedFreeBoardResponse.java
  server/src/main/java/sideeffect/project/repository/FreeBoardRepository.java
  server/src/main/java/sideeffect/project/repository/LikeRepository.java
  server/src/main/java/sideeffect/project/service/FreeBoardService.java
  server/src/test/java/sideeffect/project/controller/CommentControllerTest.java
  server/src/test/java/sideeffect/project/controller/FreeBoardControllerTest.java
  server/src/test/java/sideeffect/project/repository/FreeBoardRepositoryTest.java
  server/src/test/java/sideeffect/project/service/FreeBoardServiceTest.java
Labels: fix, refactor, update

#80 refactor: 모집 게시판 스크롤 조회 DTO 구조 변경
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardAllResponse.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardListResponse.java
  server/src/main/java/sideeffect/project/dto/recruit/RecruitBoardResponse.java
  server/src/main/java/sideeffect/project/service/RecruitBoardService.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
Labels: refactor

#81 Feat/recruit board 모집게시판 댓글 기능 구현
  server/src/main/java/sideeffect/project/common/exception/ErrorCode.java
  server/src/main/java/sideeffect/project/controller/RecruitCommentController.java
  server/src/main/java/sideeffect/project/domain/comment/RecruitComment.java
  server/src/main/java/sideeffect/project/domain/recruit/RecruitBoard.java
  server/src/main/java/sideeffect/project/dto/comment/RecruitCommentRequest.java
  server/src/main/java/sideeffect/project/dto/comment/RecruitCommentResponse.java
  server/src/main/java/sideeffect/project/dto/recruit/DetailedRecruitBoardResponse.java
  server/src/main/java/sideeffect/project/repository/RecruitCommentRepository.java
  server/src/main/java/sideeffect/project/service/RecruitCommentService.java
  server/src/test/java/sideeffect/project/controller/RecruitBoardControllerTest.java
  server/src/test/java/sideeffect/project/controller/RecruitCommentControllerTest.java
  server/src/test/java/sideeffect/project/service/RecruitCommentServiceTest.java
Labels: feat
